### ISSUE TITLE
Wlan and BT on Dell 1820 A

### ISSUE THREAD

**Issue by BerndGoetzKoenig** [kcunanan/Jared-PC#1]
Hallo from Germany,

I have the sam configuration, but the BCM94350ZAE (Dell 1820A) will only work for Wlan not for Bluetooth and only when the Intel card was before in the m.2 connector. 

When i have the Dell inside and make a Mainboard Reset then the OSX hangs (also win 10 can not start the dell) . When i remove the Dell,  insert the Intel and then put the the Dell back,  it works again. 

What can i do? Is this a Bios Problem ( I tried 1.2 and 1.5 ). Or are there various Dell 1820A cards

**Comment by BerndGoetzKoenig** [comment]
I am using your clover file.

**Comment by deeplyfriedchicken** [comment]
Hi @BerndGoetzKoenig sorry for the late reply, I wasn't aware that the BCM94350ZAE was a Dell chip, if you could send me the link that would be great.

My initial guess is that something is wrong either with that individual chip specifically, or with that brand. If you're using the exact some hardware, BIOS configuration, etc. then it's hard to debug. Do you have `verbose` mode on when booting into OSX?

**Comment by deeplyfriedchicken** [comment]
Also, I've been having issues with reliable bluetooth as of late, so I am moving to [this chip](https://www.ebay.com/itm/252319175707?ul_noapp=true) which I'm waiting to arrive.

**Comment by deeplyfriedchicken** [comment]
Hi @BerndGoetzKoenig, I don't have a good idea of how to help you if Windows isn't booting. There's likely another problem you'll need to investigate that is separate from my clover file. My repo is primarily for setting up MacOS, since Windows will boot with most hardware.

If you can provide more error logs, I'll do my best to help beyond this.

BTW: Switching to the Dell DW1560 has resolved issues with not detecting 5g networks and bluetooth. Check the updated readme for additional information
