### ISSUE TITLE
More details about the Wi-Fi module

### ISSUE THREAD

**Issue by HazemAM** [kcunanan/Jared-PC#13]
Hello. Thanks for sharing your guide!

I built a hackintosh a while ago with built-in Intel Wi-Fi card (with only BT working of course), and now looking for a macOS-supported card to activate AirDrop.

Now since your card is an M.2 one, I was wondering how you managed to connect it. Is it through replacing the built-in card, or by using another M.2 or PCI-e slot?

I'm asking this since it would be ideal to just replace the built-in card and not waste slots, but I heard some things about normal M.2 cards like these not being supported by the CNVi interface found on both your ASRock and my Gigabyte motherboards.

Also, is there a reason you changed your Wi-Fi card? Your old one is more shipping-accessible to me, so I'm wondering if you faced any problems with it, or is it still a good option?

**Comment by deeplyfriedchicken** [comment]
I would say if you can afford to use a PCIE slot it's definitely a much much easier way to go. I've tried replacing the built in WiFi module on other boards to no success so it's not something that always works.

If you have my board, then I'd say go for it / you only have one option since this board only has one PCI-e slot. If you get the Dell DW1560 I listed in my `README` on **this board** then it shouldn't be an issue. If not then, it's hard to say. Would do some more research on r/ hackintosh to see if someone has used the same wifi chip with your motherboard before dropping money. I'm guess you lose CNVi support though, but for me that hasn't really been a drawback.

> Also, is there a reason you changed your Wi-Fi card? Your old one is more shipping-accessible to me, so I'm wondering if you faced any problems with it, or is it still a good option?

The previous card WiFi worked well, but the bluetooth was very spotty and would sometimes not pick up. I reinstalled it multiple times to check, and potentially my card could have gone defective. I wouldn't recommend it as most people recommend the DW1560 instead.

Hope that answers your questions!

**Comment by HazemAM** [comment]
Thanks for your answer!

I did a little more research and apparently the CNVi-locking thing does exist, but only on Gigabyte boards. So those cards most likely wouldn't work on my board even though they do on yours. Kinda sucks, but I guess I'll have to go the PCI-e route like you said.

I was planning to convert the build to a SFF down the road, so I wanted to minimize the PCI-e peripherals, but oh well 🤷‍♂️.

Thanks again, and have a great day!
